<?php
require_once __DIR__ . '/../api/db.php';
requireOwner();
$db = getDB();
$ownerId = (int)$_SESSION['owner_id'];
$ownerName = $_SESSION['owner_name'] ?? 'Owner';

$stmt = $db->prepare("SELECT vo.*,sp.id plan_id,sp.name plan_name,sp.price_yearly,sp.duration_months,sp.included_venues,sp.features
    FROM venue_owners vo JOIN subscription_plans sp ON vo.plan_id=sp.id WHERE vo.id=?");
$stmt->execute([$ownerId]);
$owner = $stmt->fetch();
$subStmt = $db->prepare("SELECT vs.*,v.name venue_name FROM venue_subscriptions vs LEFT JOIN venues v ON v.id=vs.venue_id WHERE vs.owner_id=? ORDER BY vs.created_at DESC LIMIT 1");
$subStmt->execute([$ownerId]);
$subscription = $subStmt->fetch();
$venueStmt = $db->prepare("SELECT id,name,status FROM venues WHERE owner_id=? ORDER BY created_at");
$venueStmt->execute([$ownerId]);
$venues = $venueStmt->fetchAll();
$paymentStmt = $db->prepare("SELECT * FROM promotion_payments WHERE owner_id=? AND service_type='annual_subscription' ORDER BY created_at DESC LIMIT 10");
$paymentStmt->execute([$ownerId]);
$payments = $paymentStmt->fetchAll();
$features = json_decode($owner['features'] ?? '[]', true) ?: [];
$daysLeft = $subscription ? max(0,(int)ceil((strtotime($subscription['expires_at'])-time())/86400)) : 0;
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Annual Subscription - MeroMaidan Owner</title><link rel="stylesheet" href="../assets/css/admin.css"><style>
.subscription-hero{display:grid;grid-template-columns:1.15fr .85fr;gap:24px;padding:30px;border-radius:24px;background:linear-gradient(135deg,#0b2137,#154564);color:#fff;overflow:hidden}.eyebrow{color:#88ecaa;font-size:10px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.subscription-hero h1{font-size:36px;line-height:1.1;margin:10px 0}.subscription-hero p{color:#c4d2de;max-width:650px;line-height:1.7}.price-box{padding:25px;border:1px solid rgba(255,255,255,.15);border-radius:19px;background:rgba(255,255,255,.08)}.price-box strong{display:block;font-size:39px}.price-box span{color:#bad0df}.service-separation{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:22px 0}.service-card{padding:20px;border:1px solid #e1e8ee;border-radius:17px;background:#fff}.service-card.addon{background:#f8fafc}.service-card h3{font-size:15px;margin-bottom:7px}.service-card p{font-size:12px;color:#64748b;line-height:1.55}.status-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.status-card{padding:22px;border:1px solid #e1e8ee;border-radius:18px;background:#fff}.status-row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #edf1f4;font-size:13px}.feature-list{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:17px}.feature-list span{font-size:12px;color:#395169}.feature-list span:before{content:'✓';color:#1bb955;font-weight:900;margin-right:7px}@media(max-width:850px){.subscription-hero,.status-grid{grid-template-columns:1fr}.service-separation{grid-template-columns:1fr}.feature-list{grid-template-columns:1fr}}
</style></head><body><div class="admin-layout"><aside class="admin-sidebar"><div class="sidebar-logo"><div class="sidebar-logo-text">Mero<span>Maidan</span></div></div><nav class="sidebar-nav"><div class="nav-section-label">Venue Workspace</div><a href="index.php" class="nav-link"><span class="icon">📊</span> Dashboard</a><a href="venue.php" class="nav-link"><span class="icon">🏟️</span> Venues</a><a href="bookings.php" class="nav-link"><span class="icon">📅</span> Bookings</a><?php include __DIR__ . '/_promotion_nav.php'; ?><a href="subscription.php" class="nav-link active"><span class="icon">💳</span> Subscription</a></nav><div class="sidebar-footer"><div class="admin-user-name"><?=htmlspecialchars($ownerName)?></div><a href="../auth/logout.php" class="btn-logout">Sign Out</a></div></aside><main class="admin-main"><div class="admin-topbar"><div class="topbar-title">Annual <span>Subscription</span></div></div><div class="admin-content">
<?php if(isset($_GET['msg'])):?><div class="alert success" style="padding:13px;border-radius:12px;background:#f0fdf4;color:#166534;margin-bottom:16px">Subscription payment completed successfully.</div><?php endif;?>
<section class="subscription-hero"><div><div class="eyebrow">One plan. One clear price.</div><h1>Everything needed to manage one venue.</h1><p>The annual subscription pays for listing and operating one venue on MeroMaidan. Promotional visibility is purchased separately and never changes the features in this plan.</p><div class="feature-list"><?php foreach($features as $feature):?><span><?=htmlspecialchars($feature)?></span><?php endforeach;?></div></div><div class="price-box"><small>ANNUAL VENUE SUBSCRIPTION</small><strong>NPR <?=number_format((float)$owner['price_yearly'])?></strong><span>per year · one venue included</span><div style="margin-top:20px"><a href="../esewa/payment.php?subscription_upgrade=1&plan_id=<?=$owner['plan_id']?>" class="btn btn-green">Renew annual subscription</a></div></div></section>
<div class="service-separation"><article class="service-card"><h3>Annual venue subscription</h3><p><strong>NPR 9,999/year</strong><br>Listing and management access for one venue.</p></article><article class="service-card addon"><h3>Recommended Venue</h3><p><strong>NPR 1,000/month</strong><br>Optional location-based promotional visibility.</p></article><article class="service-card addon"><h3>Event Promotion</h3><p><strong>NPR 2,000/week</strong><br>Seven-day 1600×600 hero campaign and optional coupon.</p></article></div>
<div class="status-grid"><section class="status-card"><div class="data-card-header"><h3>Subscription status</h3><span class="badge <?=htmlspecialchars($subscription['status']??'pending')?>"><?=htmlspecialchars(ucwords(str_replace('_',' ',$subscription['status']??'Pending Payment')))?></span></div><div class="status-row"><span>Plan</span><strong><?=htmlspecialchars($owner['plan_name'])?></strong></div><div class="status-row"><span>Included venues</span><strong><?=count($venues)?> / 1</strong></div><div class="status-row"><span>Start date</span><strong><?=htmlspecialchars($subscription['starts_at']??'Not activated')?></strong></div><div class="status-row"><span>Expiry date</span><strong><?=htmlspecialchars($subscription['expires_at']??'Not activated')?></strong></div><div class="status-row"><span>Days remaining</span><strong><?=$daysLeft?></strong></div></section><section class="status-card"><div class="data-card-header"><h3>Payment history</h3></div><?php if($payments):foreach($payments as $payment):?><div class="status-row"><span><?=date('d M Y',strtotime($payment['created_at']))?> · <?=htmlspecialchars(strtoupper($payment['payment_method']))?></span><strong>NPR <?=number_format($payment['amount_npr'])?> · <?=htmlspecialchars(ucfirst($payment['status']))?></strong></div><?php endforeach;else:?><p style="color:#64748b;font-size:13px;padding:20px 0">No subscription payments recorded yet.</p><?php endif;?></section></div>
</div></main></div></body></html>
