<?php
require_once __DIR__ . '/../api/db.php';
requireSuperAdmin();
$db=getDB();syncPromotionStatuses();
$adminId=(int)$_SESSION['superadmin_id'];$adminName=$_SESSION['superadmin_name']??'Admin';$flash='';$flashType='success';
function recLabel(?string $value):string{return ucwords(str_replace('_',' ',$value??''));}
function getRec(PDO $db,int $id,bool $lock=false):array|false{
 $sql="SELECT r.*,v.name venue_name,v.city,v.district,vo.name owner_name,vo.email owner_email,
 (SELECT status FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id ORDER BY p.id DESC LIMIT 1) payment_status,
 (SELECT payment_method FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id ORDER BY p.id DESC LIMIT 1) payment_method,
 (SELECT provider_reference FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id AND p.status='paid' ORDER BY p.id DESC LIMIT 1) payment_reference,
 (SELECT paid_at FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id AND p.status='paid' ORDER BY p.id DESC LIMIT 1) paid_at
 FROM recommended_venue_promotions r JOIN venues v ON v.id=r.venue_id JOIN venue_owners vo ON vo.id=r.owner_id WHERE r.id=?".($lock?' FOR UPDATE':'');
 $s=$db->prepare($sql);$s->execute([$id]);return $s->fetch();
}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrfToken($_POST['csrf_token']??'')){http_response_code(403);die('Your session expired. Please return and try again.');}
 $id=(int)($_POST['id']??0);$action=$_POST['action']??'';$reason=trim($_POST['reason']??'');
 try{
  if(!$id)throw new RuntimeException('Recommended Venue order not found.');
  $db->beginTransaction();$item=getRec($db,$id,true);if(!$item)throw new RuntimeException('Recommended Venue order not found.');
  $paid=$item['payment_status']==='paid'&&$item['payment_method']==='esewa';
  if($action==='save'){
   $venueId=(int)($_POST['venue_id']??0);$start=$_POST['starts_at']??'';
   $v=$db->prepare("SELECT id FROM venues WHERE id=? AND owner_id=? AND status='active'");$v->execute([$venueId,$item['owner_id']]);
   if(!$v->fetchColumn())throw new RuntimeException('Choose an active venue belonging to this owner.');
   if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)||!strtotime($start))throw new RuntimeException('Choose a valid placement start date.');
   $expiry=date('Y-m-d',strtotime($start.' +1 month'));$status=$item['status'];
   if($paid&&in_array($status,['active','scheduled'],true))$status=strtotime($start)>strtotime(date('Y-m-d'))?'scheduled':'active';
   $db->prepare("UPDATE recommended_venue_promotions SET venue_id=?,starts_at=?,expires_at=?,amount_npr=1000,status=? WHERE id=?")->execute([$venueId,$start,$expiry,$status,$id]);
   $flash='Recommendation details saved. Price remains NPR 1,000 for one month.';
  }elseif($action==='activate'){
   if(!$paid)throw new RuntimeException('Activation requires a completed owner payment through mock eSewa.');
   $start=$_POST['starts_at']??date('Y-m-d');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)||strtotime($start)<strtotime(date('Y-m-d')))throw new RuntimeException('Choose today or a future start date.');
   $expiry=date('Y-m-d',strtotime($start.' +1 month'));$status=strtotime($start)>strtotime(date('Y-m-d'))?'scheduled':'active';
   $db->prepare("UPDATE recommended_venue_promotions SET starts_at=?,expires_at=?,amount_npr=1000,status=?,approved_by=?,approved_at=NOW(),rejection_reason=NULL WHERE id=?")->execute([$start,$expiry,$status,$adminId,$id]);
   $flash=$status==='active'?'Recommendation activated now for one month.':'Recommendation approved and scheduled for one month.';
  }elseif($action==='reject'){
   if($item['status']!=='pending_review')throw new RuntimeException('Only an order awaiting review can be rejected.');
   $db->prepare("UPDATE recommended_venue_promotions SET status='rejected',rejection_reason=? WHERE id=?")->execute([$reason?:'Rejected by Super Admin',$id]);$flash='Recommendation rejected.';
  }elseif($action==='suspend'){
   if(!in_array($item['status'],['pending_review','scheduled','active'],true))throw new RuntimeException('This order cannot be suspended from its current status.');
   $db->prepare("UPDATE recommended_venue_promotions SET status='suspended',rejection_reason=? WHERE id=?")->execute([$reason?:'Suspended by Super Admin',$id]);$flash='Recommendation suspended.';
  }elseif($action==='restore'){
   if(!$paid)throw new RuntimeException('Only a mock eSewa-paid order can be restored.');
   if(!in_array($item['status'],['suspended','rejected','cancelled','expired'],true))throw new RuntimeException('This order does not need restoration.');
   $db->prepare("UPDATE recommended_venue_promotions SET starts_at=CURDATE(),expires_at=DATE_ADD(CURDATE(),INTERVAL 1 MONTH),status='pending_review',approved_by=NULL,approved_at=NULL,rejection_reason=NULL WHERE id=?")->execute([$id]);$flash='Paid order restored to Pending Review.';
  }elseif($action==='cancel'){
   $db->prepare("UPDATE recommended_venue_promotions SET status='cancelled',rejection_reason=? WHERE id=?")->execute([$reason?:'Cancelled by Super Admin',$id]);$flash='Recommendation cancelled and removed from placement.';
  }elseif($action==='delete'){
   if($paid){$db->prepare("UPDATE recommended_venue_promotions SET status='cancelled',rejection_reason=? WHERE id=?")->execute([$reason?:'Archived by Super Admin; payment history preserved',$id]);$flash='Paid recommendation archived. Financial and audit history were preserved.';}
   else{$db->prepare("DELETE FROM promotion_analytics WHERE promotion_type='recommended_venue' AND promotion_id=?")->execute([$id]);$db->prepare("DELETE FROM promotion_payments WHERE service_type='recommended_venue' AND service_id=? AND status<>'paid'")->execute([$id]);$db->prepare("DELETE FROM recommended_venue_promotions WHERE id=?")->execute([$id]);$flash='Unpaid recommendation permanently deleted.';}
  }else throw new RuntimeException('Unsupported recommendation action.');
  logAudit('manage_recommended_venue','Promotions','recommended_venue',$id,$action.' Recommended Venue order');$db->commit();
  if($action!=='delete'||$paid)createNotification((int)$item['owner_id'],'owner',(int)$item['tenant_id'],'Recommended Venue Updated',$flash,'system');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$flash=$e instanceof RuntimeException?$e->getMessage():'Unable to update the recommendation safely.';$flashType='error';if(!($e instanceof RuntimeException))error_log('Recommendation admin error: '.$e->getMessage());}
}
syncPromotionStatuses();
$statusFilter=$_GET['status']??'all';$paymentFilter=$_GET['payment']??'all';
$statuses=['all','pending_payment','pending_review','scheduled','active','expired','rejected','suspended','cancelled'];
if(!in_array($statusFilter,$statuses,true))$statusFilter='all';if(!in_array($paymentFilter,['all','paid','unpaid'],true))$paymentFilter='all';
$where=[];$params=[];if($statusFilter!=='all'){$where[]='r.status=?';$params[]=$statusFilter;}
if($paymentFilter==='paid')$where[]="EXISTS(SELECT 1 FROM promotion_payments px WHERE px.service_type='recommended_venue' AND px.service_id=r.id AND px.status='paid' AND px.payment_method='esewa')";
elseif($paymentFilter==='unpaid')$where[]="NOT EXISTS(SELECT 1 FROM promotion_payments px WHERE px.service_type='recommended_venue' AND px.service_id=r.id AND px.status='paid')";
$sql="SELECT r.*,v.name venue_name,v.city,v.district,vo.name owner_name,vo.email owner_email,
 (SELECT status FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id ORDER BY p.id DESC LIMIT 1) payment_status,
 (SELECT payment_method FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id ORDER BY p.id DESC LIMIT 1) payment_method,
 (SELECT provider_reference FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id AND p.status='paid' ORDER BY p.id DESC LIMIT 1) payment_reference,
 (SELECT paid_at FROM promotion_payments p WHERE p.service_type='recommended_venue' AND p.service_id=r.id AND p.status='paid' ORDER BY p.id DESC LIMIT 1) paid_at,
 (SELECT COUNT(*) FROM promotion_analytics a WHERE a.promotion_type='recommended_venue' AND a.promotion_id=r.id AND a.event_type='impression') impressions,
 (SELECT COUNT(*) FROM promotion_analytics a WHERE a.promotion_type='recommended_venue' AND a.promotion_id=r.id AND a.event_type='click') clicks,
 (SELECT COUNT(*) FROM promotion_analytics a WHERE a.promotion_type='recommended_venue' AND a.promotion_id=r.id AND a.event_type='booking') bookings
 FROM recommended_venue_promotions r JOIN venues v ON v.id=r.venue_id JOIN venue_owners vo ON vo.id=r.owner_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY r.created_at DESC';
$s=$db->prepare($sql);$s->execute($params);$orders=$s->fetchAll();
$venuesByOwner=[];foreach($db->query("SELECT id,owner_id,name,city FROM venues WHERE status='active' ORDER BY name")->fetchAll()as$v)$venuesByOwner[(int)$v['owner_id']][]=$v;
$stats=$db->query("SELECT COUNT(*) total,SUM(status='pending_review') pending_review,SUM(status='active') active,SUM(status='scheduled') scheduled FROM recommended_venue_promotions")->fetch();
$revenue=(float)$db->query("SELECT COALESCE(SUM(amount_npr),0) FROM promotion_payments WHERE service_type='recommended_venue' AND payment_method='esewa' AND status='paid'")->fetchColumn();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recommended Venue - MeroMaidan Admin</title><link rel="stylesheet" href="../assets/css/admin.css"><style>
.tabs{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:20px}.tabs a{padding:10px 15px;border:1px solid #dbe5eb;border-radius:999px;background:#fff;color:#52677a;text-decoration:none;font-size:11px;font-weight:800}.tabs a.active{border-color:#1bb955;background:#eafaf0;color:#137c3b}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:20px}.summary article{padding:18px;border:1px solid #e1e8ee;border-radius:16px;background:#fff}.summary small{display:block;color:#718497;font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.summary strong{display:block;margin-top:7px;color:#0f2740;font-size:23px}.gateway{display:flex;justify-content:space-between;gap:15px;padding:15px 17px;margin-bottom:18px;border:1px solid #bde8ca;border-radius:14px;background:#effcf3;color:#166534;font-size:11px}.filters{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:16px}.filters select{padding:9px 13px;border:1px solid #dbe4ea;border-radius:10px;background:#fff;font:inherit;font-size:11px}.rec{padding:19px;border-bottom:1px solid #edf1f4}.rec:last-child{border-bottom:0}.head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.title{font-size:15px;color:#0f2740}.meta{margin-top:6px;color:#64748b;font-size:10px;line-height:1.65}.paid{display:inline-flex;padding:5px 9px;border-radius:999px;background:#dcfce7;color:#166534;font-size:9px;font-weight:900}.paid.unpaid{background:#fff7ed;color:#c2410c}.metrics{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.metrics span{padding:5px 8px;border-radius:8px;background:#f5f8fa;color:#52677a;font-size:9px;font-weight:800}.edit{display:grid;grid-template-columns:minmax(190px,1fr) 155px auto;gap:9px;align-items:end;margin-top:14px;padding:13px;border:1px solid #e2e9ee;border-radius:12px;background:#f8fafc}.edit label{display:grid;gap:5px;color:#64748b;font-size:9px;font-weight:800;text-transform:uppercase}.edit select,.edit input,.reason{width:100%;padding:8px;border:1px solid #d5e0e7;border-radius:8px;background:#fff;font:inherit;font-size:10px}.actions,.actions form{display:flex;gap:7px;flex-wrap:wrap}.actions{margin-top:11px}.reason{width:170px}.flash{padding:13px 15px;border-radius:11px;margin-bottom:15px;font-size:12px;font-weight:700}.flash.success{background:#effaf3;color:#166534}.flash.error{background:#fff1f2;color:#b42318}.empty{text-align:center;padding:50px 20px;color:#718497}.badge.pending_review{background:#fff7ed;color:#c2410c}.badge.scheduled{background:#eff6ff;color:#1d4ed8}.badge.expired,.badge.rejected,.badge.suspended,.badge.cancelled{background:#fef2f2;color:#b91c1c}@media(max-width:1000px){.summary{grid-template-columns:repeat(2,1fr)}.edit{grid-template-columns:1fr 1fr}.edit button{grid-column:1/-1}}@media(max-width:620px){.summary,.edit{grid-template-columns:1fr}.head,.gateway{flex-direction:column}.edit button{grid-column:auto}}
</style></head><body><div class="admin-layout"><aside class="admin-sidebar"><div class="sidebar-logo"><div><div class="sidebar-logo-text">Mero<span>Maidan</span> <span class="sidebar-badge">ADMIN</span></div><div style="font-size:10px;color:rgba(255,255,255,.4)">Super Admin Panel</div></div></div><nav class="sidebar-nav"><a href="index.php" class="nav-link">Dashboard</a><a href="venues.php" class="nav-link">Venues</a><a href="owners.php" class="nav-link">Owners</a><a href="bookings.php" class="nav-link">Bookings</a><a href="applications.php" class="nav-link">Applications</a><a href="plans.php" class="nav-link">Commercial Services</a><div class="nav-section-label">Promotions</div><a href="recommended-promotions.php" class="nav-link active">Recommended Venue</a><a href="event-promotions.php" class="nav-link">Event Campaigns</a><a href="cms.php" class="nav-link">CMS &amp; Content</a><a href="audit.php" class="nav-link">Audit Logs</a></nav><div class="sidebar-footer"><div class="admin-user-name"><?=htmlspecialchars($adminName)?></div><a href="../auth/logout.php" class="btn-logout">Sign Out</a></div></aside><main class="admin-main"><div class="admin-topbar"><div class="topbar-title">Recommended <span>Venue</span></div></div><div class="admin-content">
<div class="page-header"><h1>Recommended Venue management</h1><p>All owner orders, exact venues, mock eSewa payments, placement periods, statuses, and performance in one dedicated workspace.</p></div><div class="tabs"><a class="active" href="recommended-promotions.php">Recommended Venue</a><a href="event-promotions.php">Event Campaigns</a><a href="plans.php">Commercial model</a></div>
<?php if($flash):?><div class="flash <?=htmlspecialchars($flashType)?>"><?=htmlspecialchars($flash)?></div><?php endif;?><div class="gateway"><div><strong>Mock eSewa is the only owner payment method.</strong><br>Super Admin manages paid orders but cannot manually manufacture a successful payment.</div><span class="paid">NPR 1,000 · one month</span></div>
<section class="summary"><article><small>All orders</small><strong><?=(int)($stats['total']??0)?></strong></article><article><small>Awaiting review</small><strong><?=(int)($stats['pending_review']??0)?></strong></article><article><small>Active</small><strong><?=(int)($stats['active']??0)?></strong></article><article><small>Scheduled</small><strong><?=(int)($stats['scheduled']??0)?></strong></article><article><small>eSewa revenue</small><strong>NPR <?=number_format($revenue)?></strong></article></section>
<form class="filters" method="get"><select name="status"><option value="all">All statuses</option><?php foreach(array_slice($statuses,1)as$status):?><option value="<?=htmlspecialchars($status)?>" <?=$statusFilter===$status?'selected':''?>><?=htmlspecialchars(recLabel($status))?></option><?php endforeach;?></select><select name="payment"><option value="all">All payments</option><option value="paid" <?=$paymentFilter==='paid'?'selected':''?>>Paid by mock eSewa</option><option value="unpaid" <?=$paymentFilter==='unpaid'?'selected':''?>>Unpaid</option></select><button class="btn btn-navy btn-sm">Apply</button><a class="btn btn-ghost btn-sm" href="recommended-promotions.php">Reset</a></form>
<section class="data-card"><div class="data-card-header"><h3>All recommendation orders</h3><span><?=count($orders)?> shown</span></div><?php if($orders):foreach($orders as$order):$paid=$order['payment_status']==='paid'&&$order['payment_method']==='esewa';?><article class="rec"><div class="head"><div><div class="title"><strong><?=htmlspecialchars($order['venue_name'])?></strong> <small>#<?=(int)$order['id']?></small></div><div class="meta"><strong>Owner:</strong> <?=htmlspecialchars($order['owner_name'])?> · <?=htmlspecialchars($order['owner_email'])?><br><strong>Location:</strong> <?=htmlspecialchars($order['city'].($order['district']?' · '.$order['district']:''))?> · <strong>Period:</strong> <?=htmlspecialchars($order['starts_at']??'-')?> to <?=htmlspecialchars($order['expires_at']??'-')?><br><strong>Submitted:</strong> <?=date('d M Y, g:i A',strtotime($order['created_at']))?><?php if($order['rejection_reason']):?> · <strong>Admin note:</strong> <?=htmlspecialchars($order['rejection_reason'])?><?php endif;?></div></div><div><span class="badge <?=htmlspecialchars($order['status'])?>"><?=htmlspecialchars(recLabel($order['status']))?></span> <span class="paid <?=$paid?'':'unpaid'?>"><?=$paid?'Paid · mock eSewa':'Payment pending'?></span></div></div>
<div class="meta"><?php if($paid):?><strong>Reference:</strong> <?=htmlspecialchars($order['payment_reference'])?> · <?=date('d M Y, g:i A',strtotime($order['paid_at']))?><?php else:?>No completed payment. This order cannot be activated.<?php endif;?></div><div class="metrics"><span><?=(int)$order['impressions']?> impressions</span><span><?=(int)$order['clicks']?> clicks</span><span><?=(int)$order['bookings']?> bookings</span><span>NPR <?=number_format((float)$order['amount_npr'])?></span></div>
<form method="post" class="edit"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><label>Exact owner venue<select name="venue_id"><?php foreach($venuesByOwner[(int)$order['owner_id']]??[]as$v):?><option value="<?=(int)$v['id']?>" <?=(int)$v['id']===(int)$order['venue_id']?'selected':''?>><?=htmlspecialchars($v['name'].' · '.$v['city'])?></option><?php endforeach;?></select></label><label>One-month start<input type="date" name="starts_at" value="<?=htmlspecialchars($order['starts_at']?:date('Y-m-d'))?>" required></label><button name="action" value="save" class="btn btn-navy btn-sm">Save details</button></form>
<?php if($order['status']==='pending_review'):?><div class="actions"><form method="post"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><input class="reason" name="reason" placeholder="Rejection reason"><button name="action" value="reject" class="btn btn-red btn-sm">Reject order</button></form></div><?php endif;?>
<div class="actions"><?php if($paid&&in_array($order['status'],['pending_review','scheduled'],true)):?><form method="post"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><input type="hidden" name="starts_at" value="<?=htmlspecialchars(max(date('Y-m-d'),$order['starts_at']))?>"><button name="action" value="activate" class="btn btn-green btn-sm">Approve &amp; activate</button></form><?php endif;?><?php if(in_array($order['status'],['pending_review','scheduled','active'],true)):?><form method="post"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><input class="reason" name="reason" placeholder="Suspension reason"><button name="action" value="suspend" class="btn btn-red btn-sm">Suspend</button></form><?php endif;?><?php if($paid&&in_array($order['status'],['suspended','rejected','cancelled','expired'],true)):?><form method="post"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><button name="action" value="restore" class="btn btn-green btn-sm">Restore to review</button></form><?php endif;?><?php if(!in_array($order['status'],['cancelled','expired'],true)):?><form method="post" onsubmit="return confirm('Cancel this recommendation?')"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><button name="action" value="cancel" class="btn btn-ghost btn-sm">Cancel</button></form><?php endif;?><form method="post" onsubmit="return confirm('Remove this recommendation? Paid orders are archived, never erased.')"><input type="hidden" name="csrf_token" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$order['id']?>"><button name="action" value="delete" class="btn btn-red btn-sm"><?=$paid?'Archive':'Delete unpaid'?></button></form></div></article><?php endforeach;else:?><div class="empty"><strong>No recommendation orders match these filters.</strong><p>Owner purchases appear here as soon as they are created.</p></div><?php endif;?></section>
</div></main></div></body></html>
